[package]
name = "crust"
version = "0.1.0"
edition = "2021"

[dependencies]
# Misc
uuid = "1.10.0"
chrono = "0.4.39"
argon2 = "0.5.3"
# For GraphQL stuff
async-graphql = { version = "7.0.14", features = ["uuid", "chrono"] }
async-graphql-axum = "7.0.14"
# For HTTP Stuff
axum = "0.8.1"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.5.2", features = ["cors"] }
# For SQL Stuff
diesel = { version = "2.2.6", features = ["postgres", "postgres_backend", "uuid", "chrono", "r2d2"] }
# Config Stuff
config = "0.15.6"
# slab = "0.4.9"
# futures = "0.3.30"
