services:
  postgres:
    image: postgres:18.4-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mensatt
      POSTGRES_USER: mensatt
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?} # :? ensures value is set and non-empty
    volumes:
      # NOTE: Data from versions <= 17 needs to be migrated
      # For more details see: https://github.com/docker-library/postgres/issues/37
      - ./postgres-data:/var/lib/postgresql/
    # command: postgres -c config_file=/etc/postgresql/postgresql.conf
  mensatt:
    image: crust:latest
    build:
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      MENSATT__DATABASE__PASSWORD: ${POSTGRES_PASSWORD:?}
      MENSATT__DATABASE__HOST: postgres
    volumes:
      - ./private_key.pem:/private_key.pem
      - ./public_key.pem:/public_key.pem
